### PR TITLE
Add circle.yml

### PR DESCRIPTION
**Pull request by Fosome**
- build with CircleCi
- update Simplecov version

### CODE REVIEW

**Comment by nhunzaker** [comment]
Hey there. 😍

**Comment by Fosome** [comment]
hey handsome(s) 🍆

**Comment by ltk** [comment]
tite tite tite

**Comment by Fosome** [comment]
Worth noting, CircleCI doesn't support testing multiple rubies:  https://circleci.com/docs/unrecognized-ruby-version/

Look to just fix Travis instead?

**Comment by nhunzaker** [comment]
@Fosome I do this on a node project to test against multiple nodes:

https://github.com/vigetlabs/gangway/blob/master/circle.yml#L5-L9

Possibly similar here?

**Comment by Fosome** [comment]
@nhunzaker Something like this out there: http://www.jetthoughts.com/blog/tricks/2014/11/24/run-tests-against-multiple-ruby-versions-on-circleci.html

Feels brittle, dunno.

FWIW 1.9.3px seems so old (plenty of warnings just `bundle install`ing), maybe we should move to `>= 2.0` support, or even `>= 2.1`.

**Pull request closed without merging**
